name: CI

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer, phpunit

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Run PHPUnit
      run: vendor/bin/phpunit --coverage-text
